# Generated by Django 5.2.8 on 2025-12-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('AGUA', 'Material de Agua'), ('RESCATE', 'Material de Rescate'), ('TRAUMA', 'Material Médico'), ('EPP', 'Protección Personal'), ('COMUNICACION', 'Comunicaciones'), ('HERRAMIENTAS', 'Herramientas y Zapadores'), ('OTRO', 'Otros')], default='HERRAMIENTAS', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Cajonera 3, Bandeja superior', max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', '🟢 Operativo'), ('MANTENCION', '🟡 En Mantención'), ('BAJA', '🔴 De Baja')], default='OPERATIVO', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='carros.carro')),
            ],
        ),
    ]
