# Generated by Django 5.2.8 on 2025-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('capacidad_personal', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('BOMBA', 'Bomba'), ('ESCALA', 'Escala'), ('RESCATE', 'Rescate'), ('Z', 'Cisterna (Z)'), ('OTRO', 'Otro')], default='BOMBA', max_length=50)),
                ('estado', models.CharField(choices=[('EN_SERVICIO', 'En Servicio'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio'), ('EN_MANTENCION', 'En Mantención')], default='EN_SERVICIO', max_length=50)),
            ],
        ),
    ]
