# Generated by Django 5.2.8 on 2025-12-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='tipo',
            field=models.CharField(choices=[('BOMBA', 'Bomba'), ('ESCALA', 'Escala'), ('RESCATE', 'Rescate'), ('FORESTAL', 'Forestal'), ('Z', 'Cisterna (Z)'), ('OTRO', 'Otro')], default='BOMBA', max_length=50),
        ),
    ]
