# Generated by Django 5.2.8 on 2026-01-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_alter_carro_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano_llegada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año Llegada'),
        ),
        migrations.AddField(
            model_name='carro',
            name='capacidad_agua',
            field=models.IntegerField(default=0, verbose_name='Litros de Agua'),
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año Fabricación'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo',
            field=models.CharField(choices=[('BOMBA', 'Bomba'), ('ESCALA', 'Escala'), ('RESCATE', 'Rescate'), ('FORESTAL', 'Forestal'), ('CISTERNA', 'Cisterna (Z)'), ('OTRO', 'Otro (Comandancia/Transporte)')], default='BOMBA', max_length=50),
        ),
    ]
