# Generated by Django 5.2.8 on 2025-11-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SubTipoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_subtipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='partes.tipoemergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_emergencia', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('SubTipoEmergencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partes.subtipoemergencia')),
                ('tipo_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partes.tipoemergencia')),
            ],
        ),
    ]
