# Generated by Django 5.2.8 on 2025-11-19 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
        ('partes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='hora_extincion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='jefe_a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte',
            name='quien_anoto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_anotados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AsistenciaBombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(blank=True, max_length=100, null=True)),
                ('compania', models.CharField(blank=True, max_length=50, null=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_bomberos', to='partes.parte')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida_cuartel', models.TimeField(blank=True, null=True)),
                ('hora_llegada_emergencia', models.TimeField(blank=True, null=True)),
                ('hora_retirada_emergencia', models.TimeField(blank=True, null=True)),
                ('hora_llegada_cuartel', models.TimeField(blank=True, null=True)),
                ('km_salida', models.IntegerField(default=0)),
                ('km_llegada', models.IntegerField(default=0)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carros.carro')),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducciones', to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='partes.parte')),
            ],
        ),
    ]
