# Generated by Django 5.2.8 on 2025-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0002_parte_hora_extincion_parte_jefe_a_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='afectado_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='afectado_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='afectado_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='denunciante_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='denunciante_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
