# Generated by Django 5.2.8 on 2025-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0003_parte_afectado_nombre_parte_afectado_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='vehiculo_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='vehiculo_marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='vehiculo_modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='vehiculo_patente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='vehiculo_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
