# Generated by Django 5.2.8 on 2025-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0004_parte_vehiculo_color_parte_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parte',
            old_name='SubTipoEmergencia',
            new_name='subtipo_emergencia',
        ),
        migrations.AddField(
            model_name='parte',
            name='jefe_a_cargo_compania',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='jefe_a_cargo_rango',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
