# Generated by Django 5.2.8 on 2025-11-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0005_rename_subtipoemergencia_parte_subtipo_emergencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoyoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=50)),
                ('a_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoyos_externos', to='partes.parte')),
            ],
        ),
    ]
