# Generated by Django 5.2.8 on 2025-11-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0006_apoyoexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciacarro',
            name='conductor_compania',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asistenciacarro',
            name='conductor_rango',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asistenciacarro',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_carros', to='partes.parte'),
        ),
        migrations.AlterField(
            model_name='tipoemergencia',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
