# Generated by Django 5.2.8 on 2025-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0007_asistenciacarro_conductor_compania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('CERRADO', 'Cerrado / Aprobado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='parte',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parte',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
