# Generated by Django 5.2.8 on 2026-02-17 02:03

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0008_parte_estado_parte_latitud_parte_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='afectado_rut',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[usuarios.validators.validar_rut_chileno]),
        ),
        migrations.AlterField(
            model_name='parte',
            name='afectado_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[usuarios.validators.validar_telefono_chileno]),
        ),
        migrations.AlterField(
            model_name='parte',
            name='denunciante_rut',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[usuarios.validators.validar_rut_chileno]),
        ),
    ]
