# Generated by Django 5.2.8 on 2026-02-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0009_alter_parte_afectado_rut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='responsable_edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_por_editar', to=settings.AUTH_USER_MODEL),
        ),
    ]
