# Generated by Django 5.2.8 on 2025-11-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
