# Generated by Django 5.2.8 on 2025-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_bombero_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombero',
            name='compania',
            field=models.CharField(blank=True, choices=[('PRIMERA', 'Primera Compañía'), ('SEGUNDA', 'Segunda Compañía'), ('TERCERA', 'Tercera Compañía')], default='PRIMERA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='rango',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'Director/@'), ('CAPITAN', 'Capitán'), ('TENIENTE_1', 'Teniente Primero'), ('TENIENTE_2', 'Teniente Segundo'), ('TENIENTE_3', 'Teniente Tercero'), ('AYUDANTE', 'Ayudante de Compañía'), ('SECRETARIO', 'Secretario/@'), ('TESORERO', 'Tesorero/@'), ('VOLUNTARIO', 'Voluntario')], default='VOLUNTARIO', max_length=50, null=True),
        ),
    ]
