# Generated by Django 5.2.8 on 2025-12-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0003_alter_bombero_compania_alter_bombero_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombero',
            name='alergias',
            field=models.TextField(blank=True, help_text='Alergias a medicamentos o alimentos', null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='bombero',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('O+', 'O Positivo'), ('O-', 'O Negativo'), ('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='talla_calzado',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='talla_pantalon',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='talla_polera',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bombero',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil'),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='compania',
            field=models.CharField(choices=[('PRIMERA', 'Primera Compañía'), ('SEGUNDA', 'Segunda Compañía'), ('TERCERA', 'Tercera Compañía')], default='PRIMERA', max_length=20),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='rango',
            field=models.CharField(choices=[('VOLUNTARIO', 'Voluntario'), ('AYUDANTE', 'Ayudante'), ('TENIENTE_3', 'Teniente Tercero'), ('TENIENTE_2', 'Teniente Segundo'), ('TENIENTE_1', 'Teniente Primero'), ('CAPITAN', 'Capitán'), ('TESORERO', 'Tesorero General'), ('SECRETARIO', 'Secretario General'), ('DIRECTOR', 'Director'), ('COMANDANTE', 'Comandante')], default='VOLUNTARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
