# Generated by Django 5.2.8 on 2025-12-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_bombero_alergias_bombero_contacto_emergencia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombero',
            name='rango',
            field=models.CharField(choices=[('SUPERINTENDENTE', 'SuperIntendente'), ('VICESUPERINTENDENTE', 'ViceSuperIntendente'), ('SECRETARIOGENERAL', 'Secretario General'), ('TESOREROGENERAL', 'Tesorero General'), ('TESOREROGENERAL', 'Tesorero General'), ('COMANDANTE', 'Comandante'), ('SEGUNDOCOMANDANTE', 'Segundo Comandante'), ('SEGUNDOCOMANDANTE', 'Segundo Comandante'), ('DIRECTOR', 'Director'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('CAPITAN', 'Capitan'), ('AYUDANTE', 'Ayudante'), ('TENIENTEPRIMERO', 'Teniente Primero'), ('TENIENTESEGUNDO', 'Teniente Segundo'), ('TENIENTETERCERO', 'Teniente Tercero')], default='VOLUNTARIO', max_length=20),
        ),
    ]
