# Generated by Django 5.2.8 on 2026-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_bombero_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
