# Generated by Django 5.2.8 on 2026-01-04 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_bombero_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardiaNocturna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(unique=True, verbose_name='Mes de Guardia')),
                ('compania_responsable', models.CharField(choices=[('PRIMERA', 'Primera Compañía'), ('SEGUNDA', 'Segunda Compañía'), ('TERCERA', 'Tercera Compañía')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('voluntarios', models.ManyToManyField(related_name='guardias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
