# Generated by Django 5.2.8 on 2026-02-17 02:17

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_guardianocturna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombero',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[usuarios.validators.validar_telefono_chileno]),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='rango',
            field=models.CharField(choices=[('SUPERINTENDENTE', 'SuperIntendente'), ('VICESUPERINTENDENTE', 'ViceSuperIntendente'), ('SECRETARIOGENERAL', 'Secretario General'), ('TESOREROGENERAL', 'Tesorero General'), ('COMANDANTE', 'Comandante'), ('SEGUNDOCOMANDANTE', 'Segundo Comandante'), ('DIRECTOR', 'Director'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('CAPITAN', 'Capitan'), ('AYUDANTE', 'Ayudante'), ('TENIENTEPRIMERO', 'Teniente Primero'), ('TENIENTESEGUNDO', 'Teniente Segundo'), ('TENIENTETERCERO', 'Teniente Tercero'), ('VOLUNTARIO', 'Voluntario'), ('CENTRALISTA', 'Centralista')], default='VOLUNTARIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[usuarios.validators.validar_rut_chileno]),
        ),
        migrations.AlterField(
            model_name='bombero',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[usuarios.validators.validar_telefono_chileno], verbose_name='Teléfono Móvil'),
        ),
    ]
